### ISSUE TITLE
[0.11.1] Seems there is a bug in ModuleRunner.ignore_further_calls_to_server

### ISSUE THREAD

**Issue by Mr-indescribable** [seantis/suitable#13]
Hi,

I tested the new release 0.11.1 and I found something not works as expected.

Here, in this function: ModuleRunner.ignore_further_calls_to_server, the argument passed in as "server" is a domain name or an IP address but items in api.servers is probably in 3 formats: \<host\> or \<host:port\> or \<[ipv6]:port\>.

So this will cause the ValueError of list.remove. And it will be certainly triggered when the server is unreachable and the port is specified.

BTW, this is why I implemented the ServerContainer class in https://github.com/seantis/suitable/pull/12 .

**Comment by Mr-indescribable** [comment]
And I added IPv6 support in [my fork (in that ServerContainer :laughing: )](https://github.com/Mr-indescribable/suitable/blob/master/suitable/api.py#L32). You can view it if you are interested.

**Comment by href** [comment]
Thanks for bringing this up. I haven't considered where 'server' is used in addition to the Api constructor. I'll have a look on Monday and a fix.

**Comment by href** [comment]
Your solution still changes `Api.server` from a list to a custom class. That's something I don't want to break, because people might rely on this property being a list. That prevents me from adopting your code.

Anyway, I've added a test case and I've developed a fix. The way this works now is as I think is the most obvious. If the server `example.org:22` fails, the callback is going to be `example.org:22`. This also holds true for any results. So if I call an Api as follows:

```python
result = Api('localhost:22').command('whoami')
```
The result may be acquired thusly:
```python
result.rc('localhost:22')
```
But *not* as follows:
```python
result.rc('localhost')
```
In theory this even supports the following construct:
```python
api = Api(('host:123', 'host:456'))
```
Though Ansible decides what happens in this case (that is, it might do some grouping and we go with the flow). Suitable will ultimately take whatever strings you add to the server lists (as long as it can understand them) and then make sure that you can use the same strings for reference. The server is only split into host/port to tell Ansible more about the connection and host/port are merged again when Ansible calls back.

**Comment by href** [comment]
If you can, please have a look at the latest master btw. I'll push a release tomorrow.

**Comment by href** [comment]
I pushed the release. Feel free to reopen if the problem still occurs.

**Comment by Mr-indescribable** [comment]
>  people might rely on this property being a list

Oh, I see, I didn't consider this case.

--------------------

> have a look at the latest master

I'll have a look a few days later, thanks for the nice project.
