### ISSUE TITLE
A Suggestion about RunnerResults

### ISSUE THREAD

**Issue by Mr-indescribable** [seantis/suitable#15]
Hi, I found one more issue. Well, maybe not an issue.

-----------------------

The RunnerResults class is a subclass of dict. But in some cases, it not behaves like a dict.

We have a \_\_getattr\_\_ method in the RunnerResults class, this method is behaves like \_\_getitem\_\_, it will try to return the content that RunnerResults object contains.

But acctually, the \_\_getattr\_\_ method in the built-in dict class will not try to return the content of dict.

```python
>>> d = {'a': 1}
>>> getattr(d, 'a')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'a'
```

--------------------------

This will cause some problems. Such as dumping RunnerResults with simplejson.dumps. (In other words, the results cannot be passed through the Celery broker directly when Celery is using json serializer. And I noticed this when I use Suitable in Celery tasks.)

But, the RunnerResults is a subclass of dict isn't it? I think it's supposed to behave almost same with the dict class.

And of course we can convert it to dict before doing something, but I think there could be a better way.

So here is my suggestion: we can make RunnerResults behaves more like a dict, make \_\_getattr\_\_ not effect the content of RunnerResults.

**Comment by href** [comment]
RunnerResults is indeed like a dict and behaves mostly like one. It should actually also serialise into JSON. The following code works for me:

```python
>>> import json
>>> from suitable.runner_results import RunnerResults
>>> json.dumps(RunnerResults({'foo': 'bar'}))
'{"foo": "bar"}'
```

Of course, if you load the result again, you will get a plain dict. If you want to use the RunnerResults again you'd have to load it explicitly:

```python
>>> import json
>>> from suitable.runner_results import RunnerResults
>>> RunnerResults(json.loads('{"foo": "bar"}'))
```

> We have a __getattr__ method in the RunnerResults class, this method is behaves like __getitem__, it will try to return the content that RunnerResults object contains.

> But acctually, the __getattr__ method in the built-in dict class will not try to return the content of dict.

> So here is my suggestion: we can make RunnerResults behaves more like a dict, make __getattr__ not 
effect the content of RunnerResults.

I get your point and having a runner result which is *almost* a dict, but not quite is a bit of a leaky abstraction. The problem is that I don't see a way of having `result.rc()` / `result.rc('example.org')` work and at the same time have `__getattr__` behave exactly as it would on a normal dict. The issue is that when `result.rc` is looked up, the `__getattr__` call is triggered, at which point I don't know yet if the key `rc` exists for `example.org`, when it is requested later.

We could stop using a dict-like class altogether, but I'm not sure that's a great choice either, because Ansible does return its results as a dict and that does seem useful. Not to mention that such a change would break the current API.

**Comment by Mr-indescribable** [comment]
I regret posting this.

I feel this is a bad suggestion when I think again about it. Sorry for the bother :|
