### ISSUE TITLE
Different ports same server

### ISSUE THREAD

**Issue by accountgit** [seantis/suitable#17]
I have a bastion host that contacting to differents ports, you connect to different hosts.

If I made 

servers = ['localhost:25585','localhost:23674']
only works the first connection, the second says 
KeyError: 'localhost:25585 could not be contacted'

If I change the order of the array, the one available it's the first on the array.

Full sample:
from suitable import Api
servers = ['localhost:25585','localhost:23674']
api = Api(servers, extra_vars={'connection': 'ssh'})
result = api.command('ip a')
for server in servers:
        print result.stdout(server)

**Comment by href** [comment]
I'm afraid I won't have time to look into this until August as I am on vacation. I don't think I've ever tested this so I'll have to do that and there is a good chance that this needs some changes in the code.

**Comment by href** [comment]
This is not trivial to implement it seems. Ansible groups hosts and calls each host once by hostname (which is why you don't see multiple results being returned). However, even if I artificially create a single group for each host/port combination I do not see a change in this behaviour.

I'll have to look into this in more depth when I have the time.

Currently your best bet is to create a separate alias for each server through your hosts file or your ssh client config and use those instead.

**Comment by Daverball** [comment]
This should have already been addressed by #37
