### ISSUE TITLE
Using Ansible collections

### ISSUE THREAD

**Issue by elgow** [seantis/suitable#44]
How can I use modules in the Ansible collections. I'm especially interested in using the `ansible.builtins.file` module documented at [https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_lookup.html](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_lookup.html)

**Comment by Daverball** [comment]
I suspect this was an issue with Ansible 8+ since we didn't properly initialize the importlib machinery in order for the collections installed through `ansible` (not `ansible-core`) to be available.

suitable 0.20.0 now does this correctly.

Installing `ansible-base` can be problematic too, since it overwrites some `ansible` modules and makes them become unavailable.
