### ISSUE TITLE
Stubs, TQM & Stability?

### ISSUE THREAD

**Issue by ccrvlh** [seantis/suitable#47]
Hi @href thanks for sharing this. Been trying a few solutions to run ansible programatically (Runner, AWX, SH, etc), this is by for the best way I've found so far.

Wondering what's your experience on the stability of the Ansible internal API since you've started this (reliability concerns). I've seen quite a few articles talking about Ansible's internal API, but none of them work. I guess the biggest change was with 2.x, but haven't followed the source closely to understand how it has evolved so far.

Also, wondering if you ever had the chance to explore the `Task Queue Manager` and the `Play` class,  if I'm not mistaken those are the ones responsible for arranging units of work (tasks) in a playbook manner. Would be great if it was a straight forward solution (not sure it is).

At last, I though of adding stubs to the repo, to be able to have autocomplete and type hint on the modules.
I first tried adding a method with `overload` but as the modules are loaded dynamically it raises an `AttrbuteError`, but the stubs seem to work great. Example with the `package` module (https://github.com/seantis/suitable/compare/master...lowercase00:suitable:add)

![Screen Shot 2022-08-02 at 22 01 05](https://user-images.githubusercontent.com/21188280/182501856-65fb5922-0b1a-4795-9973-927363949e7f.png)

It could be an option to slowly write stubs for the most relevant modules (methods). What do you think about that?
Again, thanks a lot for sharing.

**Comment by href** [comment]
I'm no longer with Seantis and I haven't had a hand in this repository in two years, so changes/inclusions are not up to me. Adding stubs sounds like a good idea to me though!

About your questions: I have encountered the classes you mention, but have never worked with them. Playbooks were not much of a concern to me when creating this API as Suitable kind of works like a playbook on its own, albeit without check mode.

Also, the API is not stable at all (since it is internal) and usually there's a fair amount of going through internals after each release (or it was the case when I worked on this). It tends to be doable though. Ansible's core doesn't seem to be in much development recently as well, so I suppose it should not change drastically between releases.

Also nowadays I tend to use https://pyinfra.com/ instead, when I need to reach for a pythonic way to drive infrastructure. It's not as powerful as Ansible and doesn't have nearly as much community content supporting it, but it's programmatic model is *much* cleaner and enables one to add new modules without much ceremony.

**Comment by lowercase00** [comment]
I just found `pyinfra` but haven't had much success setting it up so far. Still have to spend some time to learn it. I really liked the idea though. I never understood why Ansible doesn't make this API stable... difficult to use it production if they change it so much.

 I've been writing a few lines to revive [Fabtools](https://github.com/fabtools/fabtools) using some ideas of Fabric, which would make the API mostly the same as this one.

```python
from xyz import Client
client = Client('hosts')
client.package(name="nano", state="present")
```

Will upload soon. Thanks for sharing, will spend more time with pyinfra!

**Comment by href** [comment]
Cheers. What really sealed the deal for me with pyinfra was how you can write operations and facts. It's trivial to write abstractions for these things:
* https://docs.pyinfra.com/en/2.x/api/operations.html#example-managing-files
* https://docs.pyinfra.com/en/2.x/api/facts.html#example-getting-the-list-of-files-in-a-directory

Only the `--dry-run` story is quite limited with pyinfra, but I guess adding proper `--check --diff` support like in Ansible would make it a lot harder to write code that is able to display differences (one would have to write such comparisons in their own operations, complicating things quite a bit).

**Comment by lowercase00** [comment]
Really interesting indeed. It soes seem that only the CLI is the first-class citizen though, maybe in the future this changes... The PythonAPI examples are not the cleanest of all, but I guess just takes some time to get used to...

**Comment by href** [comment]
That's true. I did get it to work for a private project, but you definitely have to look at the CLI portions of the code and do some boilerplate stuff. Maybe a good Python API is something you'd want to suggest to the pyinfra project. It's definitely not a focus at the moment to use this as a library, but it would be quite possible.

**Comment by lowercase00** [comment]
Ended up closing this because the conversation went to a different path, I guess it's worth to keep it open about the stubs.

**Comment by Daverball** [comment]
Stubs part continued through #52
