### ISSUE TITLE
does this suitable support playbook?

### ISSUE THREAD

**Issue by qianxi2017** [seantis/suitable#9]
cool project which make my use of ansible in python super convenient.
but i have a question, does this suitable support running playbook programmatically from python?
in my situation, i have a playbook and it's no problem to run in command-line.
i want to make it a rest api so that other project can call it.
Any help related is appreciated. Thanks

**Comment by href** [comment]
Hi there. Glad you like the project!

To answer your question: No, playbooks are not supported. I don't think there's much use in Suitable supporting running playbooks either, since this is something the Ansible commandline tools do well. Suitable is meant to be alternative to playbooks. It is not a feature-complete Ansible Python API.

For your use-case I would suggest you either dig into the Ansible API yourself (there's some possibly outdated information about it [here](http://docs.ansible.com/ansible/latest/dev_guide/developing_api.html#id3)).

Or maybe you could just run your ansible playbooks through simple commandline calls from your REST server. That way you won't have a mismatch between running your playbooks through the commandline, versus running them through the Python API. Because my guess is that there's a chance you would introduce subtle differences by using the Python API.

**Comment by qianxi2017** [comment]
Thanks a lot for your suggestions(which I will take a serious consideration), and now I realise the purpose of this project.

**Comment by href** [comment]
You're welcome. Glad I could help :)

**Comment by don2ccc** [comment]
Thank you! this is a great project! loves Ansible, also start loving suitable!

**Comment by href** [comment]
You're welcome! Glad to hear it's useful to others 😄
